CREATE TABLE IF NOT EXISTS keywords (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    group_name VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_keywords_group_name ON keywords (group_name);

CREATE TABLE IF NOT EXISTS knowledge_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    type VARCHAR(40) NOT NULL,
    group_name VARCHAR(100) NOT NULL,
    content VARCHAR(4000),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_knowledge_items_group_name ON knowledge_items (group_name);

CREATE TABLE IF NOT EXISTS assets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    type VARCHAR(40) NOT NULL,
    tag VARCHAR(120) NOT NULL,
    storage_url VARCHAR(500),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_assets_type ON assets (type);

CREATE TABLE IF NOT EXISTS personas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(80) NOT NULL,
    creator VARCHAR(80) NOT NULL,
    role_name VARCHAR(100) NOT NULL,
    tone VARCHAR(100),
    status VARCHAR(40) NOT NULL,
    prompt_template VARCHAR(4000),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_personas_status ON personas (status);

CREATE TABLE IF NOT EXISTS app_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(80) NOT NULL,
    account VARCHAR(120) NOT NULL UNIQUE,
    role_code VARCHAR(60) NOT NULL,
    role_name VARCHAR(80) NOT NULL,
    status VARCHAR(40) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_app_users_role_code ON app_users (role_code);

CREATE TABLE IF NOT EXISTS geo_tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    keyword VARCHAR(120) NOT NULL,
    status VARCHAR(40) NOT NULL,
    question_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_geo_tasks_status ON geo_tasks (status);

CREATE TABLE IF NOT EXISTS geo_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id BIGINT NOT NULL,
    keyword VARCHAR(120) NOT NULL,
    question VARCHAR(500) NOT NULL,
    ai_title VARCHAR(180) NOT NULL,
    url VARCHAR(500) NOT NULL,
    media VARCHAR(80) NOT NULL,
    description VARCHAR(1000) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_geo_results_task_id ON geo_results (task_id);

CREATE TABLE IF NOT EXISTS creations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    geo_task_id BIGINT,
    title VARCHAR(180) NOT NULL,
    brand VARCHAR(80) NOT NULL,
    platform VARCHAR(80) NOT NULL,
    summary VARCHAR(500),
    body VARCHAR(8000) NOT NULL,
    status VARCHAR(40) NOT NULL,
    publish_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_creations_status ON creations (status);
CREATE INDEX IF NOT EXISTS idx_creations_geo_task_id ON creations (geo_task_id);

CREATE TABLE IF NOT EXISTS publish_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id VARCHAR(80) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    platform_code VARCHAR(60) NOT NULL,
    platform_name VARCHAR(80) NOT NULL,
    endpoint VARCHAR(500),
    status VARCHAR(40) NOT NULL,
    expires_at DATE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_publish_accounts_platform ON publish_accounts (platform_code);

CREATE TABLE IF NOT EXISTS publish_credentials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id VARCHAR(80) NOT NULL UNIQUE,
    platform_code VARCHAR(60) NOT NULL,
    encrypted_secret VARCHAR(4000) NOT NULL,
    expired_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_publish_credentials_platform ON publish_credentials (platform_code);

CREATE TABLE IF NOT EXISTS publish_tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_id BIGINT NOT NULL,
    title VARCHAR(180) NOT NULL,
    body VARCHAR(8000) NOT NULL,
    platform_code VARCHAR(60) NOT NULL,
    platform_name VARCHAR(80) NOT NULL,
    account_id VARCHAR(80) NOT NULL,
    account_name VARCHAR(100) NOT NULL,
    scheduled_at TIMESTAMP NOT NULL,
    status VARCHAR(40) NOT NULL,
    retry_count INTEGER NOT NULL DEFAULT 0,
    max_retry_count INTEGER NOT NULL DEFAULT 3,
    last_receipt_message VARCHAR(1000),
    external_publish_id VARCHAR(160),
    publish_url VARCHAR(500),
    last_attempt_at TIMESTAMP,
    published_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_publish_tasks_status ON publish_tasks (status);
CREATE INDEX IF NOT EXISTS idx_publish_tasks_schedule ON publish_tasks (scheduled_at);
CREATE INDEX IF NOT EXISTS idx_publish_tasks_platform ON publish_tasks (platform_code);

CREATE TABLE IF NOT EXISTS publish_receipts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id BIGINT NOT NULL,
    platform_code VARCHAR(60) NOT NULL,
    account_id VARCHAR(80) NOT NULL,
    attempt_no INTEGER NOT NULL,
    success BOOLEAN NOT NULL,
    external_publish_id VARCHAR(160),
    url VARCHAR(500),
    message VARCHAR(1000) NOT NULL,
    published_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_publish_receipts_task_id ON publish_receipts (task_id);

CREATE TABLE IF NOT EXISTS audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module VARCHAR(80) NOT NULL,
    action VARCHAR(80) NOT NULL,
    target_id VARCHAR(160),
    operator_account VARCHAR(120) NOT NULL,
    operator_name VARCHAR(80) NOT NULL,
    operator_role VARCHAR(60) NOT NULL,
    client_ip VARCHAR(80) NOT NULL,
    request_uri VARCHAR(300) NOT NULL,
    success BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_audit_logs_module ON audit_logs (module);
CREATE INDEX IF NOT EXISTS idx_audit_logs_operator ON audit_logs (operator_account);
CREATE INDEX IF NOT EXISTS idx_audit_logs_created_at ON audit_logs (created_at);
